import type { Metadata } from "next";

import { emotionTheme } from "@/config/emotion";
import { muiTheme } from "@/config/mui";
import EmotionRegistry from "@/lib/emotion/registry";

import GlobalStyled from "@/components/GlobalStyled";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <EmotionRegistry
          cacheOptions={{ key: "css", prepend: false }}
          muiTheme={muiTheme}
          emotionTheme={emotionTheme}
        >
          <GlobalStyled />
          <Header />
          {children}
        </EmotionRegistry>
      </body>
    </html>
  );
}
